package com.pb.stratus.connect.services.soap.clearcache;

import javax.jws.WebParam;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2011-11-01T10:39:03.482-04:00
 * Generated source version: 2.4.3
 */
@WebService(targetNamespace = "http://www.pb.com/connect/services/soap/clearcacheservice/v1")
public interface ClearCacheService {

    public String clearCache(@WebParam(name = "tenantName") String tenantName,
                             @WebParam(name = "mapName") String mapName) throws ClearCacheServiceFault;
}
